<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            // Admin users
            [
                'name' => 'Admin',
                'email' => 'admin@gmail.com',
                'nic' => '123456789V',
                'password' => Hash::make('password'),
                'role_id' => 1,
                'mobile' => '0771234567',
                'image' => 'admin.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'System Admin',
                'email' => 'add@gmail.com',
                'nic' => '223456789V',
                'password' => Hash::make('password'),
                'role_id' => 1,
                'mobile' => '0772234567',
                'image' => 'admin2.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        
            // Staff/Lecturers
            [
                'name' => 'Dr. Smith',
                'email' => 'smith@gmail.com',
                'nic' => '987654321V',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'mobile' => '0779876543',
                'image' => 'lecturer1.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Prof. Johnson',
                'email' => 'johnson@gmail.com',
                'nic' => '887654321V',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'mobile' => '0778876543',
                'image' => 'lecturer2.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dr. Williams',
                'email' => 'williams@gmail.com',
                'nic' => '787654321V',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'mobile' => '0777876543',
                'image' => 'lecturer3.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Prof. Brown',
                'email' => 'brown@gmail.com',
                'nic' => '687654321V',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'mobile' => '0776876543',
                'image' => 'lecturer4.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dr. Davis',
                'email' => 'davis@gmail.com',
                'nic' => '587654321V',
                'password' => Hash::make('password'),
                'role_id' => 2,
                'mobile' => '0775876543',
                'image' => 'lecturer5.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        
            // Student users
            [
                'name' => 'John Doe',
                'email' => 'john@gmail.com',
                'nic' => '112233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0775556667',
                'image' => 'student1.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jane Smith',
                'email' => 'jane@gmail.com',
                'nic' => '212233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0776556667',
                'image' => 'student2.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Robert Johnson',
                'email' => 'robert@gmail.com',
                'nic' => '312233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0777556667',
                'image' => 'student3.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Emily Wilson',
                'email' => 'emily@gmail.com',
                'nic' => '412233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0778556667',
                'image' => 'student4.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Michael Brown',
                'email' => 'michael@gmail.com',
                'nic' => '512233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0779556667',
                'image' => 'student5.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sarah Davis',
                'email' => 'sarah@gmail.com',
                'nic' => '612233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0770556667',
                'image' => 'student6.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'David Miller',
                'email' => 'david@gmail.com',
                'nic' => '712233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0771556667',
                'image' => 'student7.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lisa Taylor',
                'email' => 'lisa@gmail.com',
                'nic' => '812233445V',
                'password' => Hash::make('password'),
                'role_id' => 3,
                'mobile' => '0772556667',
                'image' => 'student8.jpg',
                'is_active' => 1,
                'email_verified_at' => Carbon::now(),
                'verification_code' => null,
                'expires_at' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
